### PR TITLE
Granularizing 2020 election data for constituents and sub counties

### PR DESCRIPTION
**Pull request by hmanvcs**

### CODE REVIEW

**Comment by ssmusoke** [comment]
@hmanvcs can you remove the 2020 from the folder names, but leave them on the file names

**Comment by hmanvcs** [comment]
@ssmusoke done

**Comment by ssmusoke** [comment]
@hmanvcs I have noticed that the sub-county files have a new column subcounty_pk with values prefixed like SC70-1, can you remove it so that no new data fields are created

**Comment by hmanvcs** [comment]
I have removed the subcounty_pk column

**Pull request merged**
